service: bedrock-vonage-toolkit

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    VONAGE_API_KEY: ${env:VONAGE_API_KEY}
    VONAGE_API_SECRET: ${env:VONAGE_API_SECRET}
    VONAGE_APPLICATION_ID: ${env:VONAGE_APPLICATION_ID}
    VONAGE_PRIVATE_KEY: ${env:VONAGE_PRIVATE_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - bedrock:*
          Resource: '*'
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

functions:
  sendSMS:
    handler: src/actions/sendSMS.handler
    description: Send SMS messages via Vonage API
    events:
      - http:
          path: /send-sms
          method: post
          cors: true
  
  makeVoiceCall:
    handler: src/actions/makeVoiceCall.handler
    description: Initiate voice calls via Vonage API
    events:
      - http:
          path: /make-call
          method: post
          cors: true
  
  verifyNumber:
    handler: src/actions/verifyNumber.handler
    description: Verify phone numbers via Vonage API
    events:
      - http:
          path: /verify-number
          method: post
          cors: true
  
  checkVerification:
    handler: src/actions/checkVerification.handler
    description: Check verification status via Vonage API
    events:
      - http:
          path: /check-verification
          method: post
          cors: true

  getInsightData:
    handler: src/actions/getInsightData.handler
    description: Get number insights via Vonage API
    events:
      - http:
          path: /number-insight
          method: post
          cors: true
