openapi: 3.0.0
info:
  title: Phone Number Insight API
  version: 1.0.0
  description: API for retrieving information about phone numbers using Vonage Number Insight
paths:
  /number-insight:
    post:
      summary: Get phone number insights
      description: |
        Provides information about a phone number including:
        - Basic number information (country, format)
        - Carrier details (current and original)
        - Validity and reachability status
        - Fraud risk indicators
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phoneNumber
              properties:
                phoneNumber:
                  type: string
                  description: Phone number in E.164 format (e.g., +12025550123)
                  example: "+12025550123"
      responses:
        '200':
          description: Successful response with phone number insights
          content:
            application/json:
              schema:
                type: object
                properties:
                  phoneNumber:
                    type: string
                    description: The phone number that was analyzed
                    example: "+12025550123"
                  countryName:
                    type: string
                    description: The country the phone number belongs to
                    example: "United States"
                  currentCarrier:
                    type: object
                    description: Information about the current carrier
                    properties:
                      name:
                        type: string
                        description: The name of the current carrier
                        example: "Verizon"
                      country:
                        type: string
                        description: The country code of the current carrier
                        example: "US"
                      networkType:
                        type: string
                        description: The type of network (mobile, landline, etc.)
                        example: "mobile"
                      networkCode:
                        type: string
                        description: The network code of the current carrier
                        example: "310004"
                  originalCarrier:
                    type: object
                    description: Information about the original carrier (before porting)
                    properties:
                      name:
                        type: string
                        description: The name of the original carrier
                        example: "AT&T"
                      country:
                        type: string
                        description: The country code of the original carrier
                        example: "US"
                      networkType:
                        type: string
                        description: The type of network (mobile, landline, etc.)
                        example: "mobile"
                      networkCode:
                        type: string
                        description: The network code of the original carrier
                        example: "310410"
                  isValid:
                    type: boolean
                    description: Whether the phone number is valid
                    example: true
                  isReachable:
                    type: boolean
                    description: Whether the phone number is currently reachable
                    example: true
                  isPorted:
                    type: boolean
                    description: Whether the phone number has been ported to another carrier
                    example: false
                  isRoaming:
                    type: boolean
                    description: Whether the phone is currently roaming
                    example: false
                  roamingCountry:
                    type: string
                    description: The country where the phone is roaming (if applicable)
                    example: "CA"
                  carrierChanged:
                    type: boolean
                    description: Whether the carrier has changed (ported to a different carrier)
                    example: false
                  fraudRisk:
                    type: object
                    description: Fraud risk assessment
                    properties:
                      score:
                        type: number
                        description: Risk score (0-100, higher means more risky)
                        example: 10
                      recommendation:
                        type: string
                        description: Recommendation based on risk assessment
                        example: "allow"
        '400':
          description: Bad request - invalid phone number format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Phone number must be in E.164 format (e.g., +12025550123)"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to retrieve number insights"
