openapi: 3.0.0
info:
  title: Vonage SMS API
  description: Send SMS messages using Vonage API
  version: 1.0.0
servers:
  - url: https://your-api-gateway-url.execute-api.us-east-1.amazonaws.com/dev
    description: API Gateway endpoint
paths:
  /send-sms:
    post:
      summary: Send an SMS message
      description: Send an SMS message to a phone number using Vonage API
      operationId: sendSms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - from
                - to
                - text
              properties:
                from:
                  type: string
                  description: Sender ID or phone number (must be enabled in your Vonage account)
                  example: "YourApp"
                to:
                  type: string
                  description: Recipient phone number in E.164 format
                  example: "+12025550123"
                text:
                  type: string
                  description: Message content
                  example: "Hello from Vonage API!"
                type:
                  type: string
                  enum: [text, unicode, binary]
                  default: text
                  description: Message type
                ttl:
                  type: integer
                  minimum: 300000
                  maximum: 259200000
                  description: Message time-to-live in milliseconds (5 minutes to 3 days)
                statusReportReq:
                  type: boolean
                  default: false
                  description: Request delivery receipt
                webhookUrl:
                  type: string
                  format: uri
                  description: URL for delivery receipt webhook
                webhookMethod:
                  type: string
                  enum: [GET, POST]
                  default: POST
                  description: HTTP method for delivery receipt webhook
                clientRef:
                  type: string
                  maxLength: 40
                  description: Client reference for the message
      responses:
        '200':
          description: SMS sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  messageId:
                    type: string
                    description: Unique message identifier
                  to:
                    type: string
                    description: Recipient phone number
                  status:
                    type: object
                    properties:
                      code:
                        type: string
                        description: Status code
                      message:
                        type: string
                        description: Status message
                  remainingBalance:
                    type: string
                    description: Remaining account balance
                  messagePrice:
                    type: string
                    description: Price of the message
                  network:
                    type: string
                    description: Network code
                  deliveryStatus:
                    type: string
                    enum: [sent, failed]
                    description: Delivery status
                  errorMessage:
                    type: string
                    nullable: true
                    description: Error message if delivery failed
                  timestamp:
                    type: string
                    format: date-time
                    description: Timestamp of the request
                  messageCount:
                    type: integer
                    description: Number of message parts
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
security:
  - apiKey: []
